version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-228-252-67.eu-west-1.compute.amazonaws.com
            database: du6bmq1phclni
            schema: public
            user: dkpscptlswjycy
            password: 363636100d3320e99087108e321a148b0445e51e7adb67524746b15270bc8c90
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true