version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-70-127.eu-west-1.compute.amazonaws.com
            database: d7ekipekibctk1
            schema: public
            user: spsifwsnkkjsfe
            password: b95f414e965b9306b2a86884fdb9898e5dbbbca177586481a20e40d35353e6fc
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true